pipelines:
  - name: rpm-packaging
    manager: IndependentPipelineManager
    trigger:
      gerrit:
        - event: patchset-created
        - event: change-restored
        - event: comment-added
          comment: (?i)^(Patch Set [0-9]+:)?( [\w\\+-]*)*(\n\n)?\s*(recheck|reverify|recheck-suse)
    success:
      gerrit:
        verified: 1
    failure:
      gerrit:
        verified: -1
    success-message: Build succeeded (rpm-packaging).
    failure-message: Build failed (rpm-packaging).

projects:
  - name: openstack/rpm-packaging
    rpm-packaging:
      - openstack-upstream-gerrit-rpm-packaging-Master
      - openstack-upstream-gerrit-rpm-packaging-Mitaka
      - openstack-upstream-gerrit-rpm-packaging-Newton

jobs:
  - name: openstack-upstream-gerrit-rpm-packaging-Master
    voting: true
    branch: master
    failure-pattern: https://build.opensuse.org/project/monitor/home:suse-cloud-ci:rpm-packaging-openstack-Master-{build.build_set.commit}
    success-pattern: https://build.opensuse.org/project/monitor/home:suse-cloud-ci:rpm-packaging-openstack-Master-{build.build_set.commit}

  - name: openstack-upstream-gerrit-rpm-packaging-Mitaka
    voting: true
    branch: stable/mitaka
    failure-pattern: https://build.opensuse.org/project/monitor/home:suse-cloud-ci:rpm-packaging-openstack-Mitaka-{build.build_set.commit}
    success-pattern: https://build.opensuse.org/project/monitor/home:suse-cloud-ci:rpm-packaging-openstack-Mitaka-{build.build_set.commit}

  - name: openstack-upstream-gerrit-rpm-packaging-Newton
    voting: true
    branch: stable/newton
    failure-pattern: https://build.opensuse.org/project/monitor/home:suse-cloud-ci:rpm-packaging-openstack-Newton-{build.build_set.commit}
    success-pattern: https://build.opensuse.org/project/monitor/home:suse-cloud-ci:rpm-packaging-openstack-Newton-{build.build_set.commit}
