---
- name: Setup repositories on the deployer node
  hosts: hosts
  gather_facts: False

  vars:
    clouddata_server: provo-clouddata.cloud.suse.de
    download_suse_server: download.suse.de
    cloudsource: SUSE-OpenStack-Cloud-8-devel-staging
    arch: x86_64
    repos_url: "http://{{ clouddata_server }}/repos/{{ arch }}"
    sshpass_repo: "http://download.suse.de/ibs/QA:/SLE12SP3/update/"

  tasks:
  # SLES repos
  - name: Add SLES12SP3-Pool zypper repo
    zypper_repository:
      repo: "{{ repos_url }}/SLES12-SP3-Pool"
      name: SLES12SP3-Pool

  - name: Add SLES12SP3-Updates zypper repo
    zypper_repository:
      repo: "{{ repos_url }}/SLES12-SP3-Updates"
      name: SLES12SP3-Updates

  # Devel:Cloud:8
  - name: "Add {{ cloudsource }} media"
    zypper_repository:
      repo: "{{ repos_url }}/{{ cloudsource }}"
      name: DC8S-Media

  - name: Repo for sshpass
    zypper_repository:
      repo: "{{ sshpass_repo }}"
      name: sshpass

  # Refresh all repos
  - name: Refresh zypper repositories
    zypper_repository:
      repo: '*'
      auto_import_keys: yes
      runrefresh: yes

  - name: Install sshpass
    zypper:
      name: 'sshpass'
      state: present

  - name: Remove Repo for sshpass
    zypper_repository:
      repo: "{{ sshpass_repo }}"
      name: sshpass
      state: absent

  # NOTE: ansible's zypper extra_args are only supported in >= 2.4 and even if that version,
  # adding --replacefiles does not work
  # FIXME: Resolve the file conflicts in the ardana packages and use the zypper module
  - name: Install ardana pattern
    command: zypper -n in patterns-cloud-ardana
