---
  product:
    version: 2

  baremetal:
    subnet: 192.168.245.0
    netmask: 255.255.255.0

  servers:

    - id: deployer
      ip-addr: {{ deployer_mgmt_ip }}
      role: STD-ARDANA-ROLE
      server-group: RACK1
      mac-addr: b2:72:8d:ac:7c:6f
      ilo-ip: 192.168.109.3
      ilo-password: password
      ilo-user: admin
      nic-mapping: HEAT

    - id: osc-0001
      ip-addr: {{ controller_mgmt_ips[0] }}
      role: STD-OSC-CONTROLLER-ROLE
      server-group: RACK1
      mac-addr: d6:70:c1:36:43:f7
      ilo-ip: 192.168.109.5
      ilo-password: password
      ilo-user: admin
      nic-mapping: HEAT

    - id: dbmq-0001
      ip-addr: {{ controller_mgmt_ips[1] }}
      role: STD-DBMQ-CONTROLLER-ROLE
      server-group: RACK2
      mac-addr: d6:70:c1:36:43:f7
      ilo-ip: 192.168.109.5
      ilo-password: password
      ilo-user: admin
      nic-mapping: HEAT

    - id: mml-0001
      ip-addr: {{ controller_mgmt_ips[2] }}
      role: STD-MML-CONTROLLER-ROLE
      server-group: RACK3
      mac-addr: 52:54:00:aa:04:01
      ilo-ip: 192.168.109.5
      ilo-password: password
      ilo-user: admin
      nic-mapping: HEAT

    - id: comp-0001
      ip-addr: {{ compute_mgmt_ips[0] }}
      role: STD-COMPUTE-ROLE
      server-group: RACK2
      mac-addr: 8e:8e:62:a6:ce:76
      ilo-ip: 192.168.109.6
      ilo-password: password
      ilo-user: admin
      nic-mapping: HEAT
