---
- name: Create ceph secrets
  copy:
    dest: "/tmp/ceph-secrets.yaml"
    content: |
      ---
      apiVersion: v1
      kind: Secret
      metadata:
        name: {{ suse_osh_deploy_storage.adminSecretName }}
        namespace: {{ suse_osh_deploy_storage.adminSecretNamespace }}
      type: "kubernetes.io/rbd"
      data:
        key: {{ ceph_admin_keyring_b64key }}
      ---
      apiVersion: v1
      kind: Secret
      metadata:
        name: {{ suse_osh_deploy_storage.userSecretName }}
        namespace: {{ suse_osh_deploy_storage.userSecretNamespace }}
      type: "kubernetes.io/rbd"
      data:
        key: {{ ceph_user_keyring_b64key }}
      #---
      #apiVersion: v1
      #kind: Secret
      #metadata:
      #  name: pvc-ceph-cephfs-client-key
      #  namespace: openstack
      #type: "kubernetes.io/cephfs"
      #data:
      #  key: {{ ceph_user_keyring_b64key }}

- name: Create ceph storage class
  copy:
    dest: "/tmp/ceph-storage-classes.yaml"
    content: |
      ---
      kind: StorageClass
      apiVersion: storage.k8s.io/v1
      metadata:
        name: general
      provisioner: kubernetes.io/rbd
      parameters:
        monitors: {{ suse_osh_deploy_ceph_mons }}
        adminId: {{ suse_osh_deploy_storage.adminId }}
        adminSecretName: {{ suse_osh_deploy_storage.adminSecretName }}
        adminSecretNamespace: {{ suse_osh_deploy_storage.adminSecretNamespace }}
        pool: {{ suse_osh_deploy_storage.pool }}
        userId: {{ suse_osh_deploy_storage.userId }}
        userSecretName: {{ suse_osh_deploy_storage.userSecretName }}
        userSecretNamespace: {{ suse_osh_deploy_storage.userSecretNamespace }}
      #---
      #apiVersion: storage.k8s.io/v1
      #kind: StorageClass
      #metadata:
      #  name: cephfs
      #provisioner: ceph.com/cephfs
      #parameters:
      #  adminId: admin
      #  adminSecretName: pvc-ceph-cephfs-client-key
      #  adminSecretNamespace: openstack
      #  monitors: "{% for ip in ceph_monitors_ips %}{{ ip }}:6789{% if not loop.last %},{% endif %}{% endfor %}"
      #reclaimPolicy: Delete
      #volumeBindingMode: Immediate

- name: "Apply ceph {{ item }}"
  command: kubectl apply -f /tmp/ceph-{{ item }}.yaml --overwrite=true
  with_items:
    - secrets
    - storage-classes
