heat_template_version: 2016-10-14

resources:
  # networks
  network_mgmt:
    type: OS::Neutron::Net
    properties:
      port_security_enabled: False
  network_ardana:
    type: OS::Neutron::Net
    properties:
      port_security_enabled: False
  network_external:
    type: OS::Neutron::Net
    properties:
      port_security_enabled: False

  # subnet
  subnet_mgmt:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: network_mgmt }
      cidr: "192.168.245.0/24"
      allocation_pools:
          - start: "192.168.245.2"
            end: "192.168.245.100"
      ip_version: 4
      gateway_ip: 192.168.245.1
  subnet_ardana:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: network_ardana }
      cidr: "192.168.110.0/24"
      allocation_pools:
          - start: "192.168.110.2"
            end: "192.168.110.100"
      ip_version: 4
      gateway_ip: null
  subnet_external:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: network_external }
      allocation_pools:
          - start: "172.31.0.2"
            end: "172.31.255.154"
      cidr: "172.31.0.0/16"
      enable_dhcp: False
      gateway_ip: 172.31.0.1

  # router
  router_mgmt:
    type: OS::Neutron::Router
    properties:
      external_gateway_info:
        network: floating

  router_mgmt_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: router_mgmt }
      subnet_id: { get_resource: subnet_mgmt }

  router_external_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: router_mgmt }
      subnet_id: { get_resource: subnet_external }

  # floating IPs
  deployer-floatingip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: floating
