---
  product:
    version: 2

  baremetal:
    subnet: 192.168.245.0
    netmask: 255.255.255.0

  servers:

    - id: deployer
      ip-addr: {{ deployer_mgmt_ip }}
      hostname: deployer
      role: ARDANA-ROLE
      server-group: RACK1
      mac-addr: b2:72:8d:ac:7c:6f
      ilo-ip: 192.168.109.3
      ilo-password: password
      ilo-user: admin
      nic-mapping: HEAT

    - id: ccn-0001
      ip-addr: {{ controller_mgmt_ips[0] }}
      role: CONTROLLER-ROLE
      server-group: RACK1
      mac-addr: d6:70:c1:36:43:f7
      ilo-ip: 192.168.109.5
      ilo-password: password
      ilo-user: admin
      nic-mapping: HEAT

    - id: ccn-0002
      ip-addr: {{ controller_mgmt_ips[1] }}
      role: CONTROLLER-ROLE
      server-group: RACK2
      mac-addr: d6:70:c1:36:43:f7
      ilo-ip: 192.168.109.5
      ilo-password: password
      ilo-user: admin
      nic-mapping: HEAT

    - id: ccn-0003
      hostname: core3
      ip-addr: {{ controller_mgmt_ips[2] }}
      role: CONTROLLER-ROLE
      server-group: RACK3
      mac-addr: 26:67:3e:49:5a:a7
      ilo-ip: 192.168.109.5
      ilo-password: password
      ilo-user: admin
      nic-mapping: HEAT

    - id: COMPUTE-0001
      hostname: comp1
      ip-addr: {{ compute_mgmt_ips[0] }}
      role: COMPUTE-ROLE
      server-group: RACK1
      mac-addr: 8e:8e:62:a6:ce:76
      ilo-ip: 192.168.109.6
      ilo-password: password
      ilo-user: admin
      nic-mapping: HEAT

    - id: COMPUTE-0002
      ip-addr: {{ compute_mgmt_ips[1] }}
      role: COMPUTE-ROLE
      server-group: RACK2
      mac-addr: 8e:8e:62:a6:ce:76
      ilo-ip: 192.168.109.7
      ilo-password: password
      ilo-user: admin
      nic-mapping: HEAT

    - id: COMPUTE-0003
      ip-addr: {{ compute_mgmt_ips[2] }}
      role: COMPUTE-ROLE
      server-group: RACK3
      mac-addr: 22:f1:9d:ba:2c:2d
      ilo-ip: 192.168.109.8
      ilo-password: password
      ilo-user: admin
      nic-mapping: HEAT
