---
  product:
    version: 2

  networks:
    - name: ARDANA-NET
      vlanid: 101
      tagged-vlan: false
      cidr: 192.168.110.0/24
      addresses:
        - 192.168.110.10-192.168.110.200
      gateway-ip: 192.168.110.1
      network-group: ARDANA

    - name: MANAGEMENT-NET
      vlanid: 102
      tagged-vlan: false
      cidr: 192.168.245.0/24
      gateway-ip: 192.168.245.1
      network-group: MANAGEMENT

    - name: EXTERNAL-VM-NET
      vlanid: 103
      network-group: EXTERNAL-VM
