---
- name: Initialize the Deployer
  hosts: hosts
  gather_facts: False

  environment:
    ARDANA_INIT_AUTO: 1
    ARDANA_DEPLOYER_MEDIA_LEGACY_LAYOUT: False

  tasks:
  - name: Download ardana-init.bash
    get_url:
      url: https://raw.githubusercontent.com/SUSE-Cloud/automation/ardana-ci/ardana/ardana-init.bash
      dest: /var/lib/ardana/ardana-init.bash
      mode: 0775
      owner: ardana
    become: true
    become_user: ardana

  - name: Call ardana-init.bash
    shell: /var/lib/ardana/ardana-init.bash
    become: true
    become_user: ardana
